server.port = 8080
server.servlet.context-path=/brava

# Additional supported versions can be added here using commas like: 2.1,2.0,1.3, etc
brapi.schema.versions=2.1

# Here use '_' for all .'s in versions of BrAPI to load properly
brapi.schema.urls.v2_1.core=https://api.swaggerhub.com/apis/PlantBreedingAPI/BrAPI-Core/2.1/swagger.yaml?resolved=false&flatten=false
brapi.schema.urls.v2_1.germplasm=https://api.swaggerhub.com/apis/PlantBreedingAPI/BrAPI-Germplasm/2.1/swagger.yaml?resolved=false&flatten=false
brapi.schema.urls.v2_1.genotyping=https://api.swaggerhub.com/apis/PlantBreedingAPI/BrAPI-Genotyping/2.1/swagger.yaml?resolved=false&flatten=false
brapi.schema.urls.v2_1.phenotyping=https://api.swaggerhub.com/apis/PlantBreedingAPI/BrAPI-Phenotyping/2.1/swagger.yaml?resolved=false&flatten=false

#Other schema version imports go here.  Schema URLs will be loaded into the application on startup